---
downloads: ~/.cache/ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - ansible
  - autoconf
  - bash-completion
  - bat
  - curl
  - fasd
  - fd
  - fzf
  - gettext
  - git
  - github/gh/gh
  - go
  - gpg
  - hyperfine
  - iperf
  - jq
  - neovim
  - openssl
  - pv
  - readline
  - ssh-copy-id
  - starship
  - tmux
  - watch
  - wget

# We don't need to tap the core repo anymore
homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - autodesk-fusion360
  - cyberduck
  - docker
  - firefox
  - iterm2
  - kicad
  - raycast
  - spotify
  - stats
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1440147259, name: "AdGuard for Safari" }
  - { id: 497799835, name:  "Xcode" }
  - { id: 1444383602, name: "GoodNotes" }
  - { id: 1099568401, name: "Home Assistant" }
  - { id: 1519867270, name: "Refined GitHub" }
  - { id: 803453959, name:  "Slack" }
  - { id: 1475387142, name: "Tailscale" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
