---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yaml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yaml"
      tags: ["always"]

    - name: Ensure necessary directories exist
      block:
        - import_tasks: tasks/dev-dirs.yaml
        - import_tasks: tasks/xdg-dirs.yaml
      tags: ["dirs"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]
    - role: linuxhq.macos.iterm2
      when: configure_iterm2
      tags: ["iterm2"]

  tasks:
    - import_tasks: tasks/sudoers.yaml
      when: configure_sudoers
      tags: ["sudoers"]

    - import_tasks: tasks/gpg.yaml
      tags: ["gpg"]

    - import_tasks: tasks/osx.yaml
      when: configure_osx
      tags: ["osx"]

    - import_tasks: tasks/extra-packages.yaml
      tags: ["extra-packages"]

    - import_tasks: tasks/keyboard-layout.yaml
      tags: ["keyboard-layout"]

    - name: Run post-provision task files in a block.
      tags: ["post"]
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
