---
- name: Ensure XDG directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    recurse: true
  loop:
    - "{{ ansible_env.HOME }}/.local/share"
    - "{{ ansible_env.HOME }}/.local/bin"
    # - "{{ ansible_env.HOME }}/.config"
